---

- name: DC | Enable LDAP diagnostics
  ansible.windows.win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Diagnostics
    value: "16 LDAP Interface Events"
    data: 2
    datatype: dword
  when: harden_win_dc_ldap_diag

- name: DC | Enforce LDAP signing
  ansible.windows.win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters
    value: ldapserverintegrity
    data: 2
    datatype: dword
  when: harden_win_dc_ldap_enforce_signing
