---

- name: Set powershell.exe process mitigation
  ansible.windows.win_shell: Set-ProcessMitigation -Name powershell.exe -Enable DEP, EmulateAtlThunks, AuditDynamicCode, EnableExportAddressFilter

- name: Check powershell.exe process mitigation
  ansible.windows.win_shell: Get-ProcessMitigation -Name powershell.exe
