---
# https://twitter.com/tanmayg/status/1030513697209217024
# https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus

- name: Check if MpCmdRun exists
  ansible.windows.win_stat:
    path: "C:\\ProgramFiles\\Windows Defender\\MpCmdRun.exe"
  register: mpcmdrun

- name: Ensure Windows Defender MAPS can communicate with cloud
  ansible.windows.win_command: "\"C:\\ProgramFiles\\Windows Defender\\MpCmdRun.exe\" -validatemapsconnection"
  when: mpcmdrun.stat.exists

- name: Check Defender status
  ansible.windows.win_shell: Get-MpComputerStatus
  failed_when: false

- name: Check signatures set
  ansible.windows.win_shell: "(Get-MpThreatCatalog).ThreatName | Group { $_.Split(':')[0] } | Sort Count -Descending"
  failed_when: false
