---

- name: Add wef collector server to Event Log readers local group
  win_user:
    name: "{{ harden_win_wef_collector_server_user }}"
    state: present
    groups_action: add
    groups:
      - Event Log Readers
    when: harden_win_wef_collector_server_user is defined and harden_win_wef_collector_server_user

- name: upload WEF configuration template
  win_template:
    src: "{{ item }}"
    dest: "{{ harden_win_temp_dir }}\\{{ item | win_basename }}"
    backup: yes
  with_items: "{{ harden_win_wef_templates_list }}"

- name: Configure WEF subscriptions
  win_command: "wecutil cs {{ harden_win_temp_dir }}\\{{ item | win_basename }}"
  with_items: "{{ harden_win_wef_templates_list }}"
