---
name: Report a security issue
description: You found a security issue
title: "Security: "
labels: ["security", "triage needed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue. If issue is sensitive, please use web form or GitHub private vulnerability reporting as per SECURITY.md.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: affected
    attributes:
      label: Affected version(s)
      description: Commit, tag or release affected
    validations:
      required: false
  - type: textarea
    id: findings
    attributes:
      label: What did you found?
      description: Precise and detailed steps (include screenshots) that created the problem
      placeholder: Tell us what you see!
      value: "pop!"
    validations:
      required: true
  - type: dropdown
    id: securitytype
    attributes:
      label: Type
      description: What kind of security issue did you find?
      options:
        - Security Incident
        - Vulnerability
        - Other
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce issue?
      description: Step-by-step instructions to reproduce the issue, eventually with Proof-of-concept or exploit code.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log(s) output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: mitigations
    attributes:
      label: Mitigations or workarounds.
      description: Any condition(s) that limit impact of the issue?
  - type: textarea
    id: known
    attributes:
      label: Is issue public? exploited in the wild?
      description: Whether this vulnerability is public or known to third parties. If it is, please provide details.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
# https://github.com/github/securitylab/blob/main/docs/report-template.md
