---

- name: Packer playbook
  hosts: all
  vars:
    jumpbox_tools:
      - putty
      - filezilla
      - googlechrome
      - rdcman
      - rsat
      - 7zip
      - notepadplusplus
    harden_win_applocker_policy: "applocker-medium.xml"
  roles:
    - juju4.harden_windows
  tasks:
    - name: Install jump box toolset
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item }}"
        state: present
      with_items: "{{ jumpbox_tools }}"
