# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
## http://kitchen.ci/blog/test-kitchen-windows-test-flight-with-vagrant/
## https://atlas.hashicorp.com/boxes/search?provider=virtualbox&q=windows&sort=&utf8=%E2%9C%93
## initial ansible preparation?
    config.vm.box = "mwrock/Windows2012R2"
    config.vm.guest = :windows
    config.vm.communicator = "winrm"
    #config.winrm.username = "IEUser"
    #config.winrm.password = "Passw0rd!"
    config.vm.boot_timeout = 600

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.sudo = false
#       ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
       ansible.groups = {
          "myrole" => ["vhardenwin" ],
       }
    end

## FIXME! WARN  WinRM::WinRMWebService : [WinRM] connection failed, terminating (#<WinRM::WinRMHTTPTransportError: Unable to parse WinRM response: Missing end tag for 'META' (got "HEAD")
#    config.vm.provision :serverspec do |spec|
#        spec.pattern = '../../test/integration/default/serverspec/*_spec.rb'
#    end
    config.vm.define "vhardenwin" do |vhardenwin|
        vhardenwin.vm.hostname = "vhardenwin"
        vhardenwin.vm.provider "virtualbox" do |v|
          v.memory = 2048
        end
        vhardenwin.gui = true
    end

end

